### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by jasonronalddavis** [learn-co-curriculum/my-collect#32]
I believe there's a glitch within the last question of the Enumerators Code Challenge quiz (section 7, module 5) When I test 3 out of the 4 answers in ruby, all return true however, my answer was marked wrong. A screenshare coach couldn't give me an answer. Can IT review this and advise?

Thank you

**Comment by lizbur10** [comment]
Hello -- thank you for providing feedback! I have checked this out and the quiz is correctly scored. 

The first option is changing each word to upcase (`word.upcase`) and then evaluating that result, which will be truthy. It will return true regardless of whether the words in the array are uppercase. 

The second option returns an error because there is no `upcase?` method in Ruby. 

The fourth option also always return true because it is evaluating the words themselves, and all strings in Ruby (including empty strings!) are truthy. 

The third option is the only one that is evaluating each word to determine whether it is all uppercase and returning true if it finds any that are.

As always, thanks for contributing! 💙
